gdaxAuth:
    key: someKey
    secret: someSecret
    passphrase: somePassphrase
gdaxSandboxAuth:
    key: someKey
    secret: someSecret
    passphrase: somePassphrase
strategy: macd
granularity: 60
product: LTC-USD
stopLoss: .05
allowedSlippage: .007
