
# REQUIRED:
# GDAX Authentication
gdax_auth:
    key: someKey
    secret: someSecret
    passphrase: somePassphrase

# REQUIRED:
# trade indicator to use
# options: [macd, slowStochastic, rsi]
strategies:
    - slowStochastic
    - rsi

# REQUIRED:
# trade/analyze interval in seconds
# options: [60, 300, 900, 3600, 21600, 86400]
granularity: 60

# REQUIRED: 
# product to trade
# options: [LTC-USD, BTC-USD, ETH-USD]
product: LTC-USD

# REQUIRED:
# create a stop loss of the provided percentage, if not defined, the 24hr low will be used
stopLoss: .05

# OPTIONAL:
# GDAX Authentication for SANDBOX environment
# MUST be set if `sandbox: true`
gdax_sandbox_auth:
    key: someKey
    secret: someSecet
    passphrase: somePassphrase

# OPTIONAL:
# Run bot in a test environment (monopoly money)
sandbox: true

# OPTIONAL:
# Maximum trading funds allowed, defaults to 95% wallet amount (to leave room for fees)
# ** some trades will not succeed if the trade size is too small, don't set maxFunds too low
maxFunds: 100
