
# REQUIRED:
# GDAX Authentication
# =====================================
gdaxAuth:
    key: someKey
    secret: someSecret
    passphrase: somePassphrase

# REQUIRED
# filename of your strategy file OR of an already provided strategy the .js ext is optional
# the bot will always look relative to the ./lib/strategies directory
# ex: my-strategy, bestStrategy.js, macd, rsi
# =====================================
strategy: macd

# REQUIRED:
# trade/analyze interval in seconds
# options: [60, 300, 900, 3600, 21600, 86400]
# =====================================
granularity: 60

# REQUIRED:
# product to trade
# options: [LTC-USD, BTC-USD, ETH-USD]
# =====================================
product: LTC-USD

# REQUIRED:
# create a stop loss of the provided percentage.
# =====================================
stopLoss: .05

# REQUIRED:
# Allowed slippage percent when buying
# Bot will stop trying to buy if the order price would exceed the allowedSlippage
# =====================================
allowedSlippage: .007

# OPTIONAL:
# GDAX Authentication for SANDBOX environment
# MUST be set if `sandbox: true`
# =====================================
# gdaxSandboxAuth:
#     key: someKey
#     secret: someSecret
#     passphrase: somePassphrase

# OPTIONAL:
# Run bot in a test environment
# =====================================
# sandbox: true

# OPTIONAL:
# Maximum trading funds allowed, defaults to 95% wallet amount (to leave room for fees)
# ** some trades will not succeed if the trade size is too small, don't set maxFunds too low
# =====================================
# maxFunds: 100

# OPTIONAL:
# Dates for backtesting. if end_date is not set, today's date will be used
# format must be ISO8601
# =====================================
# backtest:
#     start_date: 2018-02-10T00:00:00Z
#     end_date: null
#     slippage: .02
